import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from 'react';
import type {
  Broker,
  CaptationLead,
  Contract,
  DocumentItem,
  FinanceEntry,
  MockClient,
  MockProperty,
  MockVisit,
  Owner,
  Proposal,
} from '../mocks/schema';
import {
  mockBrokers,
  mockClients,
  mockContracts,
  mockDocuments,
  mockFinance,
  mockLeads,
  mockOwners,
  mockProperties,
  mockProposals,
  mockVisits,
} from '../mocks';

/**
 * Holds every demo-only domain (no real backend) in plain React state,
 * seeded from the static fixtures generated by scripts/generate-mocks.ts.
 * Create/update/delete here only ever touch this in-memory state — never
 * server.ts/database.json — matching the "don't touch the API" constraint
 * while still making the screens feel interactive for a demo.
 */
interface DemoDataContextValue {
  brokers: Broker[];
  owners: Owner[];
  properties: MockProperty[];
  clients: MockClient[];
  visits: MockVisit[];
  contracts: Contract[];
  proposals: Proposal[];
  documents: DocumentItem[];
  leads: CaptationLead[];
  finance: FinanceEntry[];

  upsertLead: (lead: CaptationLead) => void;
  deleteLead: (id: string) => void;
  upsertProposal: (proposal: Proposal) => void;
  updateContractStatus: (id: string, status: Contract['status']) => void;
  upsertMockProperty: (property: MockProperty) => void;
  deleteMockProperty: (id: string) => void;
  upsertMockClient: (client: MockClient) => void;
  deleteMockClient: (id: string) => void;
  upsertMockVisit: (visit: MockVisit) => void;
  deleteMockVisit: (id: string) => void;
}

const DemoDataContext = createContext<DemoDataContextValue | null>(null);

export function DemoDataProvider({ children }: { children: ReactNode }) {
  const [brokers] = useState<Broker[]>(mockBrokers);
  const [owners] = useState<Owner[]>(mockOwners);
  const [properties, setProperties] = useState<MockProperty[]>(mockProperties);
  const [clients, setClients] = useState<MockClient[]>(mockClients);
  const [visits, setVisits] = useState<MockVisit[]>(mockVisits);
  const [contracts, setContracts] = useState<Contract[]>(mockContracts);
  const [proposals, setProposals] = useState<Proposal[]>(mockProposals);
  const [documents] = useState<DocumentItem[]>(mockDocuments);
  const [leads, setLeads] = useState<CaptationLead[]>(mockLeads);
  const [finance] = useState<FinanceEntry[]>(mockFinance);

  const upsertLead = useCallback((lead: CaptationLead) => {
    setLeads((prev) => {
      const exists = prev.some((l) => l.id === lead.id);
      return exists ? prev.map((l) => (l.id === lead.id ? lead : l)) : [lead, ...prev];
    });
  }, []);

  const deleteLead = useCallback((id: string) => {
    setLeads((prev) => prev.filter((l) => l.id !== id));
  }, []);

  const upsertProposal = useCallback((proposal: Proposal) => {
    setProposals((prev) => {
      const exists = prev.some((p) => p.id === proposal.id);
      return exists ? prev.map((p) => (p.id === proposal.id ? proposal : p)) : [proposal, ...prev];
    });
  }, []);

  const updateContractStatus = useCallback((id: string, status: Contract['status']) => {
    setContracts((prev) => prev.map((c) => (c.id === id ? { ...c, status } : c)));
  }, []);

  const upsertMockProperty = useCallback((property: MockProperty) => {
    setProperties((prev) => {
      const exists = prev.some((p) => p.id === property.id);
      return exists ? prev.map((p) => (p.id === property.id ? property : p)) : [property, ...prev];
    });
  }, []);

  const deleteMockProperty = useCallback((id: string) => {
    setProperties((prev) => prev.filter((p) => p.id !== id));
  }, []);

  const upsertMockClient = useCallback((client: MockClient) => {
    setClients((prev) => {
      const exists = prev.some((c) => c.id === client.id);
      return exists ? prev.map((c) => (c.id === client.id ? client : c)) : [client, ...prev];
    });
  }, []);

  const deleteMockClient = useCallback((id: string) => {
    setClients((prev) => prev.filter((c) => c.id !== id));
  }, []);

  const upsertMockVisit = useCallback((visit: MockVisit) => {
    setVisits((prev) => {
      const exists = prev.some((v) => v.id === visit.id);
      return exists ? prev.map((v) => (v.id === visit.id ? visit : v)) : [visit, ...prev];
    });
  }, []);

  const deleteMockVisit = useCallback((id: string) => {
    setVisits((prev) => prev.filter((v) => v.id !== id));
  }, []);

  const value = useMemo(
    () => ({
      brokers,
      owners,
      properties,
      clients,
      visits,
      contracts,
      proposals,
      documents,
      leads,
      finance,
      upsertLead,
      deleteLead,
      upsertProposal,
      updateContractStatus,
      upsertMockProperty,
      deleteMockProperty,
      upsertMockClient,
      deleteMockClient,
      upsertMockVisit,
      deleteMockVisit,
    }),
    [
      brokers,
      owners,
      properties,
      clients,
      visits,
      contracts,
      proposals,
      documents,
      leads,
      finance,
      upsertLead,
      deleteLead,
      upsertProposal,
      updateContractStatus,
      upsertMockProperty,
      deleteMockProperty,
      upsertMockClient,
      deleteMockClient,
      upsertMockVisit,
      deleteMockVisit,
    ],
  );

  return <DemoDataContext.Provider value={value}>{children}</DemoDataContext.Provider>;
}

export function useDemoData() {
  const ctx = useContext(DemoDataContext);
  if (!ctx) throw new Error('useDemoData must be used within DemoDataProvider');
  return ctx;
}
